In [91]:
import numpy as np

def counting_islands(m,n):
    '''
    m*n matirx
    '''
    matrix = np.random.randint(0,2,(m,n))
    print(matrix)
    return np.sum(matrix@np.ones((n,m)), axis=0)[0]

In [93]:
counting_islands(78,122)

[[1 0 1 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 [0 1 0 ... 0 1 1]
 ...
 [1 1 1 ... 1 1 0]
 [0 1 1 ... 1 0 1]
 [0 1 0 ... 0 1 0]]


4777.0